#!/bin/bash


if [[ -z $1 ]]; then
file="test"
else
file=$1
fi

echo "Target $file.cc"
source build $file

if [[ "$EXIT_CODE" == "0" ]]; then
  echo "---- build passed ----"
  ./zhsr
else
  echo "---- build failed ----"
fi